# Generated by Django 3.1 on 2020-08-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created_on',
            new_name='last_update',
        ),
    ]
